/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/patients": {
    /** Creates new patient with the provided metadata and dicom images */
    post: {
      parameters: {
        formData: {
          /** Patienten-Metadata as JSON-String */
          formData: string;
          /** The .dcm picture data */
          dicom_file: unknown;
        };
      };
      responses: {
        /** Accepted */
        202: {
          schema: string;
        };
      };
    };
  };
}

export interface operations {}

export interface external {}
